from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

import structlog
import torch
from datasets import Dataset, load_dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import (
    AutoModelForCausalLM,
    AutoProcessor,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
)

logger = structlog.get_logger()


@dataclass
class TrainingConfig:
    base_model_id: str = "microsoft/Phi-3.5-vision-instruct"
    output_dir: str = "./checkpoints"
    num_epochs: int = 3
    per_device_train_batch_size: int = 2
    per_device_eval_batch_size: int = 2
    gradient_accumulation_steps: int = 4
    learning_rate: float = 2e-4
    warmup_ratio: float = 0.03
    eval_split: float = 0.1
    load_in_4bit: bool = True          # QLoRA
    lora_rank: int = 16
    lora_alpha: int = 32
    lora_dropout: float = 0.05
    lora_target_modules: list[str] = field(
        default_factory=lambda: ["q_proj", "k_proj", "v_proj", "o_proj"]
    )
    attn_implementation: str = "sdpa"   # "sdpa" | "eager" | "flash_attention_2"
    mlflow_experiment: str = "visual-finetune-lab"


class LoRATrainer:
    """
    Fine-tunes a vision-language model (default: Phi-3.5-Vision) using LoRA/QLoRA
    on top of a JSONL dataset generated by SyntheticDatasetGenerator.

    The trainer:
      - Loads the base model in 4-bit (QLoRA) to run on consumer GPUs / Colab
      - Attaches LoRA adapters only to attention projection layers
      - Trains with HuggingFace Trainer + gradient accumulation
      - Saves the best checkpoint by eval loss
      - Reports all metrics to MLflow automatically (via env var MLFLOW_TRACKING_URI)

    Example:
        config = TrainingConfig(num_epochs=3, lora_rank=16)
        trainer = LoRATrainer(config)
        trainer.train(dataset_path=Path("data/datasets/invoices.jsonl"))
    """

    def __init__(self, config: TrainingConfig):
        self.config = config

    def train(self, dataset_path: Path) -> Path:
        os.environ.setdefault("MLFLOW_EXPERIMENT_NAME", self.config.mlflow_experiment)

        logger.info("loading_base_model", model=self.config.base_model_id)
        model, processor = self._load_model()

        logger.info("loading_dataset", path=str(dataset_path))
        dataset = self._prepare_dataset(dataset_path, processor)

        peft_model = self._apply_lora(model)
        trainer = self._build_trainer(peft_model, processor, dataset)

        logger.info("training_start", epochs=self.config.num_epochs)
        trainer.train()

        best_ckpt = Path(self.config.output_dir) / "best"
        peft_model.save_pretrained(best_ckpt)
        processor.save_pretrained(best_ckpt)
        logger.info("training_complete", checkpoint=str(best_ckpt))
        return best_ckpt

    # ------------------------------------------------------------------ #

    def _load_model(self):
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=self.config.load_in_4bit,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )
        processor = AutoProcessor.from_pretrained(
            self.config.base_model_id,
            trust_remote_code=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            self.config.base_model_id,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
            torch_dtype=torch.bfloat16,
            attn_implementation=self.config.attn_implementation,
        )
        model.config.use_cache = False
        return model, processor

    def _apply_lora(self, model):
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=self.config.lora_rank,
            lora_alpha=self.config.lora_alpha,
            lora_dropout=self.config.lora_dropout,
            target_modules=self.config.lora_target_modules,
            bias="none",
        )
        peft_model = get_peft_model(model, lora_config)
        trainable, total = peft_model.get_nb_trainable_parameters()
        logger.info(
            "lora_applied",
            trainable_params=trainable,
            total_params=total,
            trainable_pct=round(trainable / total * 100, 2),
        )
        return peft_model

    def _prepare_dataset(self, path: Path, processor) -> Dataset:
        raw = load_dataset("json", data_files=str(path), split="train")

        def tokenize(batch):
            texts = [
                f"User: {q}\nAssistant: {a}"
                for q, a in zip(batch["question"], batch["answer"])
            ]
            tokens = processor.tokenizer(
                texts,
                truncation=True,
                max_length=512,
                padding="max_length",
            )
            tokens["labels"] = tokens["input_ids"].copy()
            return tokens

        tokenized = raw.map(tokenize, batched=True, remove_columns=raw.column_names)
        split = tokenized.train_test_split(test_size=self.config.eval_split, seed=42)
        return split

    def _build_trainer(self, model, processor, dataset) -> Trainer:
        args = TrainingArguments(
            output_dir=self.config.output_dir,
            num_train_epochs=self.config.num_epochs,
            per_device_train_batch_size=self.config.per_device_train_batch_size,
            per_device_eval_batch_size=self.config.per_device_eval_batch_size,
            gradient_accumulation_steps=self.config.gradient_accumulation_steps,
            learning_rate=self.config.learning_rate,
            warmup_ratio=self.config.warmup_ratio,
            evaluation_strategy="epoch",
            save_strategy="epoch",
            load_best_model_at_end=True,
            metric_for_best_model="eval_loss",
            report_to=["mlflow"],
            bf16=torch.cuda.is_bf16_supported(),
            fp16=not torch.cuda.is_bf16_supported(),
            logging_steps=10,
            dataloader_num_workers=2,
        )
        return Trainer(
            model=model,
            args=args,
            train_dataset=dataset["train"],
            eval_dataset=dataset["test"],
            tokenizer=processor.tokenizer,
        )
